### PR TITLE
Jls add multimedia

### PR DESCRIPTION
**Pull request by ecstech-admin**
Per [Monday task](https://blackberg-group.monday.com/boards/1931719392/pulses/5596770318)

- added new card to multimedia
- created thumb from YouTube video
- linked to video

### CODE REVIEW

**Review by ronald-bbg — COMMENTED** [review]
Looks good with the new content! Minor padding/margins below to match figma more closely:
1) Move man illustration lower
2) Increase spacing between carousel buttons
3) Increase margins between the rows within Our Team

(Figma screenshots for reference):

Screenshot 2023-11-30 at 1 13 31 PM
Screenshot 2023-11-30 at 1 13 46 PM
Screenshot 2023-11-30 at 1 13 54 PM


Branch rende
Screenshot 2023-11-30 at 1 17 00 PM
rs:
Screenshot 2023-11-30 at 1 17 04 PM
Screenshot 2023-11-30 at 1 17 10 PM

**Comment by ecstech-admin** [comment]
implemented RP comments

**Comment by ecstech-admin** [comment]
Added YouTube modal functionality

**Review by ronald-bbg — APPROVED** [review]
Looks good!

**Review by will-bbg — APPROVED** [review]

**Pull request merged**
