### PR TITLE
Bugfix/rp 5771238558/508 fixes

### PR DESCRIPTION
**Pull request by ronald-bbg**
Achieved 100 accessibility score with the following changes:

- Adding accessible names to buttons
- Updating map graphic to reflect color contrast fixes on VISN header texts (received passing scores on color contrast tool)
- Optimized map with tinypng
- Adding H tag classnames for proper hierarchy order

Files to move after merge:
styles.css
index.html
initiative-sites.html
header.html
header-sub.html

Monday task: https://blackberg-group.monday.com/boards/5749055412/pulses/5771238558

Notes: I updated the color on the old svg file in figma. Reached out to @ecstech-admin to help fix state white borders and remove map shadows and help with resizing in photoshop to best match production. I don't currently have photoshop installed so we can sync with @will-bbg for best workflow in modifying images in future for similar updates.

Other fixes (console errors):
- Added top header dropdown arrow fix

Pending fix:
I can create a ticket and work with Jim to update the fonts path issues in a new branch

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
I'd suggest removing images we aren't using - like the extra map svg's and png's

**Comment by ronald-bbg** [comment]
Another note to improve SEO - we can remove <meta name="robots" content="noindex,nofollow"> and the empty meta description tag

and for production update with:

<meta name="description" content="VHA Uber Health Connect Initiative
Expanding Health Care Access for Veterans">

We can achieve 100 for SEO with this update SB vs Prod:
Screenshot 2024-01-25 at 6 32 34 AM


@ecstech-admin I can sync with you re sb vs prod changes in the index.html file

**Comment by will-bbg** [comment]
Why not just use the description text from production and add to the repo. 

Also, because of the no follow meta tag, this page does not rely much on SEO rankings. The page is supposed to be visible only to people that know the url.

**Comment by ronald-bbg** [comment]
It appears production has an empty meta description tag here: 

Screenshot 2024-01-25 at 6 41 33 AM

SB would keep the same code so that it doesn't get indexed for SEO. We would have to update production separately if we wanted to increase the SEO score.

**Comment by will-bbg** [comment]
Add this as the description text, “The Department of Veterans Affairs' (VA) Veterans Health Administration Innovation Ecosystem, partnered with the Veteran Transportation Program (VTP) and Uber Health to establish the VHA-Uber Health Connect Initiative (VUHC) to offer rideshare as a supplemental transportation option for Veterans and their caregivers to get to and from their medical appointments using the Uber rideshare platform.”

**Comment by ronald-bbg** [comment]
Thanks @will-bbg we increased SEO score with the new description and can remove nofollow indexing on production for 100.

Screenshot 2024-01-25 at 7 03 02 AM

**Comment by will-bbg** [comment]
We will not be removing the no follow tag. As mentioned in a comment above, the page is not supposed to be indexed. **Do not remove the no follow tag**.

**Comment by ronald-bbg** [comment]
Got it - we will leave as is for production, thanks for confirming.

**Review by will-bbg — APPROVED** [review]

**Pull request merged**
